# Generated by Django 1.11.2 on 2018-01-01 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_object_id', models.CharField(max_length=10)),
                ('cast_time', models.DateTimeField(auto_now_add=True)),
                ('vote_type', models.CharField(max_length=12)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
