# Generated by Django 1.10.5 on 2017-04-12 01:47
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User

def copy_first_name (apps, schema_editor):
    for user in User.objects.all():
        user.profile.display_name = user.first_name
        user.first_name = ""
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_display_name'),
    ]

    operations = [
        migrations.RunPython(copy_first_name),
    ]
