# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 16:12
from __future__ import unicode_literals

from django.db import migrations, models
from user_profile.models import Profile, generate_id

def fill_user_ids (apps, schema_editor):
    for profile in Profile.objects.all():
        if profile.profile_id == "":
            profile.profile_id = generate_id()
            profile.save()

def remove_user_ids (apps, schema_editor):
    pass

# Before migration, profile has:
#   id: incrimenting number which was the primary key
#   user_id: incrementing number which corresponds with the user this profile is for (unique)
# After migration, profile has:
#   profile_id: 6 digits b64, primary key
#   user_id: doesn't change

class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20170412_0147'),
    ]

    operations = [
        # Add id in four steps across two migrations
        # Before this runs profile_id should be models.CharField(max_length=6, default="")
        # 1, add it as blank for everyone
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(default="", max_length=6, serialize=False),
        ),
        # 2, update it to be correct for everyone
        migrations.RunPython(
            code=fill_user_ids,
            reverse_code=remove_user_ids,
        ),
        # At this point the model needs to be updated with primary_key=True and default=generate_id
        # models.CharField(primary_key=True, max_length=6, default=generate_id)

        # Also, if using mysql, the following line of SQL must be run:
        # ALTER TABLE user_profile_profile DROP PRIMARY KEY, CHANGE COLUMN id id int(11) PRIMARY KEY;
    ]
