# Generated by Django 1.11.2 on 2019-01-13 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_add_profile_ids_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(to='user_profile.Profile'),
        ),
    ]
