# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20190113_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='program.Program'),
        ),
    ]
