# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import program.models

# Replace create thumbnail urls for programs in the form program/PROG_ID.png
def update_url_program(apps, schema_editor):
    programs = apps.get_model("program", "Program").objects.all()
    for p in programs:
        if (p.image.name.endswith("nophoto.png")):
            p.image.name = "program/nophoto.png"
        else:
            p.image.name = "program/{}.png".format(p.program_id)
        p.save()
    print("Database media urls have been updated to point to program/PROG_ID.png.")
    print("These files were NOT automatically moved. Please ensure they exist in exec/program/PROG_ID.png")


def update_url_program_thumbnails(apps, schema_editor):
    programs = apps.get_model("program", "Program").objects.all()
    for program in programs:
        if (program.image.name.endswith("nophoto.png")):
            program.image.name = "program_thumbnails/nophoto.png"
        else:
            program.image.name = "program_thumbnails/{}.png".format(program.program_id)
        program.save()
    print("Database media urls have been updated to point to program_thumbnails/PROG_ID.png.")
    print("These files were NOT automatically moved. Please ensure they exist in MEDIA_ROOT/program_thumbnails/PROG_ID.png")

class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_program_image'),
    ]

    operations = [
        migrations.RunPython(
            code=update_url_program,
            reverse_code=update_url_program_thumbnails,
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(default='program/nophoto.png', storage=program.models.OverwriteStorage(), upload_to=program.models.get_image_path),
        ),
    ]
