# Generated by Django 1.11.2 on 2019-01-13 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20190113_0634'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif',
            name='source_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.Program'),
        ),
        migrations.AlterField(
            model_name='notif',
            name='source_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment'),
        ),
    ]
